// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIb-HUdYAICOVTmueto6EmCNRL6hFt-Rs',
    appId: '1:740964389489:web:bce71192205fab0158c1d0',
    messagingSenderId: '740964389489',
    projectId: 'vester-cb750',
    authDomain: 'vester-cb750.firebaseapp.com',
    storageBucket: 'vester-cb750.appspot.com',
    measurementId: 'G-TG6GC3DQ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKd9AlvXt7taRLmMddg6DXULZWWNv-pgA',
    appId: '1:740964389489:android:bfdcb679b514886958c1d0',
    messagingSenderId: '740964389489',
    projectId: 'vester-cb750',
    storageBucket: 'vester-cb750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknJKOcARcJkFey8fyDra1ACHMt33SKDQ',
    appId: '1:740964389489:ios:5866d65c25356bc658c1d0',
    messagingSenderId: '740964389489',
    projectId: 'vester-cb750',
    storageBucket: 'vester-cb750.appspot.com',
    iosClientId:
        '740964389489-6elhegt9s7ooge4qh7tgeaovgsbplgbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vesterDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknJKOcARcJkFey8fyDra1ACHMt33SKDQ',
    appId: '1:740964389489:ios:5866d65c25356bc658c1d0',
    messagingSenderId: '740964389489',
    projectId: 'vester-cb750',
    storageBucket: 'vester-cb750.appspot.com',
    iosClientId:
        '740964389489-6elhegt9s7ooge4qh7tgeaovgsbplgbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vesterDriver',
  );
}
